### ISSUE TITLE
Authentication key fails, but it never prompted me to supply one.

### ISSUE THREAD

**Issue by carterbox** [StephenSwat/GMR-Linux#1]
```
$ python ./gmr-client
Traceback (most recent call last):
  File "./gmr-client", line 4, in <module>
    gmr.app.main()
  File "/home/carterbox/Documents/GMR-Linux-master/gmr/app.py", line 16, in main
    userAccount = account.Account(config.config.get("GMR", "AuthKey"))
  File "/home/carterbox/Documents/GMR-Linux-master/gmr/account.py", line 23, in __init__
    raise ValueError("Authentication key did not authenticate.")
ValueError: Authentication key did not authenticate.
$
```

OK, so I found the file in the `.local` directory that holds the AuthKey variable and I pasted my key there. Then I ran it again, but this time:

```
[My Game]
[]
Traceback (most recent call last):
  File "gmr-client", line 4, in <module>
    gmr.app.main()
  File "/home/chingd/Documents/GMR-Linux-master/gmr/app.py", line 21, in main
    userAccount.getCurrentTurns()[0].playTurn()
IndexError: list index out of range
```

Why is it not prompting me to set up my account through the UI?

**Comment by carterbox** [comment]
I recently revisited this project, and I figured out that there was no UI opened because it was never completed. Thus, I made some tweaks to add text based functionality. #2
